version: '3.1'
services:
  product-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  product-adminer:
    image: adminer
    ports:
      - ${MYSQL_ADMINER_PORT}:8080

  product-redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379