spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testProductdb;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;IGNORECASE=TRUE;MODE=MySQL
    username: sa
    password: sa

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  redis:
    host: 127.0.01
    port: 6379
    database: 3

  cache:
    type: redis

  flyway:
    enabled: false
